services:
  - type: web
    name: rtmd-api
    env: docker
    plan: free
    dockerfilePath: RealTimeMongoDashboard.API/Dockerfile
    envVars:
      - key: ASPNETCORE_ENVIRONMENT
        value: Production
      - key: Mongo__ConnectionString
        sync: false
      - key: Mongo__Database
        value: rtmd
      - key: Jwt__Issuer
        value: rtmd-api
      - key: Jwt__Audience
        value: rtmd-clients
      - key: Jwt__Key
        sync: false
      - key: Jwt__ExpiryMinutes
        value: "120"
      - key: Jwt__Internal__ApiKey
        sync: false
    healthCheckPath: /swagger/index.html
  - type: worker
    name: rtmd-watcher
    env: docker
    plan: free
    dockerfilePath: RealTimeMongoDashboard.Watcher/Dockerfile
    envVars:
      - key: Mongo__ConnectionString
        sync: false
      - key: Mongo__Database
        value: rtmd
      - key: Mongo__Collections__0
        value: orders
      - key: Mongo__Collections__1
        value: users
      - key: Mongo__Collections__2
        value: metrics
      - key: Api__BaseUrl
        # e.g. https://rtmd-api.onrender.com
        sync: false
      - key: Api__InternalKey
        sync: false
