services:
  - type: web
    name: realtime-mongo-api
    env: docker
    plan: free
    rootDir: src/API
    dockerfilePath: ./src/API/Dockerfile
    autoDeploy: true
    envVars:
      - key: MongoDb__ConnectionString
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: InternalAuth__Key
        sync: false

  - type: worker
    name: realtime-mongo-watcher
    env: docker
    plan: free
    rootDir: src/Watcher
    dockerfilePath: ./src/Watcher/Dockerfile
    autoDeploy: true
    envVars:
      - key: MongoDb__ConnectionString
        sync: false
      - key: Jwt__Key
        sync: false
      - key: Jwt__Issuer
        sync: false
      - key: InternalAuth__Key
        sync: false
